version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  labels:
  - backend
  - dependencies
- package-ecosystem: npm
  directory: "/src/frontend"
  schedule:
    interval: monthly
    time: "13:00"
  labels:
  - frontend
  - dependencies
  ignore:
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.21
    - 14.14.22
    - 14.14.31
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.167
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
- package-ecosystem: docker
  directory: "/src/backend"
  schedule:
    interval: daily
    time: "13:00"
  labels:
  - dependencies
  ignore:
  - dependency-name: python
    versions:
    - 3.9.1.pre.alpine
    - 3.9.2.pre.alpine
    - 3.9.3.pre.alpine
